In [39]:
import numpy as np

In [40]:
# Creación de matrices
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
type(matrix1)

numpy.ndarray

In [42]:
# Otra forma de crear matrices
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
type(matrix2)

numpy.matrix

In [44]:
# Multiplicación matricial
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B


array([[19, 22],
       [43, 50]])

In [45]:
# Multiplicación elemento a elemento
A*B

array([[ 5, 12],
       [21, 32]])

In [46]:
# Determinante de una matriz
np.linalg.det(A)


-2.0000000000000004

In [47]:
# Acceso a los elementos de una matriz
A[0,0]


1

In [48]:
A[0,1]


2

In [49]:
# Matriz identidad
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [50]:
I2@A


array([[1., 2.],
       [3., 4.]])

In [51]:
A@I2


array([[1., 2.],
       [3., 4.]])

In [52]:
# Transpuesta de una matriz
A.T


array([[1, 3],
       [2, 4]])

In [53]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [54]:
# Inversa de una matriz
C = np.linalg.inv(A)
C


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
A@C


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [56]:
C@A


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [57]:
# Eigenvalores y eigenvectores
eigenvals, eigenvecs = np.linalg.eig(A)

In [58]:
eigenvals

array([-0.37228132,  5.37228132])

In [59]:
eigenvecs

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [60]:
l0 = eigenvals[0]

In [61]:
v0 = eigenvecs[:,0]
v0 

array([-0.82456484,  0.56576746])

In [62]:
A@v0 

array([ 0.30697009, -0.21062466])

In [63]:
v0*l0 

array([ 0.30697009, -0.21062466])

In [64]:
# Matrices diagonales
diagonal = np.diag([1,2,3,4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [65]:
l1 = eigenvals[1]
v1 = eigenvecs[:,1]
v1*l1

array([-2.23472698, -4.88542751])

In [66]:
A@v1

array([-2.23472698, -4.88542751])

In [67]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [68]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [69]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [70]:
eigenvecs@np.diag(eigenvals)

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [71]:
np.isclose(np.linalg.inv(eigenvecs)@A@eigenvecs, np.diag(eigenvals))

array([[ True,  True],
       [ True,  True]])

In [72]:
# Concatenación de matrices

D = np.array([[1,2],[3,4]])
E = np.array([[5,6],[7,8]])

np.vstack((D,E))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
np.hstack((D,E))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Solución automática de sistemas de ecuaciones

In [74]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 1],
              [3, 2]])

# Right-hand side vector B
B = np.array([8, 11])


In [75]:
# Solve the linear system of equations
solution = np.linalg.solve(A, B)

# The solution contains the values for the variables
print("Solution (x, y):", solution)


Solution (x, y): [ 5. -2.]


In [76]:
A@solution

array([ 8., 11.])