In [245]:
import numpy as np

In [246]:
# Creación de matrices
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [247]:
type(matrix1)

numpy.ndarray

In [248]:
# Otra forma de crear matrices
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [249]:
type(matrix2)

numpy.matrix

In [250]:
# Multiplicación matricial
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B


array([[19, 22],
       [43, 50]])

In [251]:
# Multiplicación elemento a elemento
A*B

array([[ 5, 12],
       [21, 32]])

In [252]:
# Determinante de una matriz
np.linalg.det(A)


-2.0000000000000004

In [253]:
# Acceso a los elementos de una matriz
A[0,0]


1

In [254]:
A[0,1]


2

In [255]:
# Matriz identidad
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [256]:
I2@A


array([[1., 2.],
       [3., 4.]])

In [257]:
A@I2


array([[1., 2.],
       [3., 4.]])

In [258]:
# Transpuesta de una matriz
A.T


array([[1, 3],
       [2, 4]])

In [259]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [260]:
# Inversa de una matriz
C = np.linalg.inv(A)
C


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [261]:
A@C


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [262]:
C@A


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [263]:
# Eigenvalores y eigenvectores
eigenvals, eigenvecs = np.linalg.eig(A)

In [264]:
eigenvals

array([-0.37228132,  5.37228132])

In [265]:
eigenvecs

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [266]:
l0 = eigenvals[0]

In [267]:
v0 = eigenvecs[:,0]
v0 

array([-0.82456484,  0.56576746])

In [268]:
A@v0 

array([ 0.30697009, -0.21062466])

In [269]:
v0*l0 

array([ 0.30697009, -0.21062466])

In [270]:
# Matrices diagonales
diagonal = np.diag([1,2,3,4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [271]:
l1 = eigenvals[1]
v1 = eigenvecs[:,1]
v1*l1

array([-2.23472698, -4.88542751])

In [272]:
A@v1

array([-2.23472698, -4.88542751])

In [273]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [274]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [275]:
A@eigenvecs

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [276]:
eigenvecs@np.diag(eigenvals)

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [277]:
np.isclose(np.linalg.inv(eigenvecs)@A@eigenvecs, np.diag(eigenvals))

array([[ True,  True],
       [ True,  True]])

In [278]:
# Concatenación de matrices

D = np.array([[1,2],[3,4]])
E = np.array([[5,6],[7,8]])

np.vstack((D,E))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [279]:
np.hstack((D,E))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])