In [7]:
import numpy as np

In [8]:
# Creación de matrices
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(matrix1)

numpy.ndarray

In [10]:
# Otra forma de crear matrices
matrix2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
type(matrix2)

numpy.matrix

In [12]:
# Multiplicación matricial
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A@B


array([[19, 22],
       [43, 50]])

In [13]:
# Multiplicación elemento a elemento
A*B

array([[ 5, 12],
       [21, 32]])

In [15]:
# Determinante de una matriz
np.linalg.det(A)


-2.0000000000000004

In [17]:
# Acceso a los elementos de una matriz
A[0,0]


1

In [18]:
A[0,1]


2

In [19]:
# Matriz identidad
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [20]:
I2@A


array([[1., 2.],
       [3., 4.]])

In [21]:
A@I2


array([[1., 2.],
       [3., 4.]])

In [22]:
# Transpuesta de una matriz
A.T


array([[1, 3],
       [2, 4]])

In [23]:
# Inversa de una matriz
C = np.linalg.inv(A)
C


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
A@C


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [25]:
C@A


array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])